language: go
go:
  - 1.1
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get launchpad.net/gocheck
  - go get github.com/nu7hatch/gouuid
  - go get -v ./...
  - go build -v ./...
  - go test -i ./...
